// Barrel for the shared UI primitives — import several with one line:
//   import {Card, Pill, Eyebrow, Avatar} from '@/components/ui';
export {default as Section} from './section';
export {default as Eyebrow} from './eyebrow';
export {default as Heading} from './heading';
export {default as Text} from './text';
export {default as Prose} from './prose';
export {default as SectionHeading} from './section-heading';
export {default as Pill} from './pill';
export {default as Avatar} from './avatar';
export {default as PersonByline} from './person-byline';
export {default as Card} from './card';
export {default as CardStat} from './card-stat';
export {default as PriceTag} from './price-tag';
export {Button, buttonVariants} from './button';
export {default as MultiSelect, type MultiSelectOption} from './multi-select';
export {default as ScrollArea} from './scroll-area';
export {default as MetaPill} from './meta-pill';
export {default as ReadingTime} from './reading-time';
export {default as PublishDate} from './publish-date';
